### ISSUE TITLE
Hard-coded dependency on bash

### ISSUE THREAD

**Issue by felixbuenemann** [wbyoung/avn-nvm#5]
Why does avn-nvm hard code bash as the shell for sourcing nvm?
Couldn't it just use `process.env.SHELL`?

It took me quite a while to figure out why avn was failing although nvm was working fine, because I had only installed nvm in zsh but not in bash.

**Comment by wbyoung** [comment]
It's not hard-coded. It's based on the [configuration files that are in use](https://github.com/wbyoung/avn/blob/cb40d68ce11bd47e8f6ccd7a8e1ec8f4a2d673a1/lib/setup/profile.js#L51).

Which shell do you use? Both for different reasons? You installed both `avn` and `nvm` in `zsh`? Also, do you have a `~/.zshrc` file? Did you have one when you first installed?

**Comment by felixbuenemann** [comment]
I am only actively using zsh and have a .zshrc, but bash is also installed.

I was referring to: https://github.com/wbyoung/avn-nvm/blob/master/index.js#L16

**Comment by wbyoung** [comment]
Oh, that makes sense. Would you be interested in making that change, testing it, and sending over a pull request?

**Comment by felixbuenemann** [comment]
I'll give it a shot. Sorry for not referring to the exact code in the first post.

**Comment by wbyoung** [comment]
No worries. Thanks!
